### PR TITLE
New DT Settings

### PR DESCRIPTION
**Pull request by prykon**
Creating tiles and custom fields just got a whole much easier!

Also, all setting changes are done through jQuery and API so the page doesn't need to reload. This makes changing settings faster and less confusing.

**Create custom tiles and fields**
https://user-images.githubusercontent.com/36511666/223449221-ec64348d-5c27-4a30-9271-5bd1bc34fd25.mov

**Edit tiles, fields and translations**
https://user-images.githubusercontent.com/36511666/223450756-bdc9fb65-c2c6-4dc3-88be-0f51e722b2f2.mov

**Tile and Field Search**
https://user-images.githubusercontent.com/36511666/223452233-2fad91de-c2c1-462b-9405-9c5bb44a9011.mov

**Functionality List:**
- Create custom tiles
- Create custom fields
- Sort tiles
- Sort custom fields
- Edit tiles
- Edit custom fields
- Translate tiles
- Translate fields
- Tile preview pane
- Custom field search

### CODE REVIEW

**Comment by corsacca** [comment]
### Tile Settings
- Tile Description
- V2? Tile Description Translations
- V2: Tile Custom display options

image


### Field Settings
- Default name shows custom name. And Custom Name is empty
- v2: Ability to select icon.

image


### Field Option Settings
- Show Default label 
- Show icon
- V2 Icon selection

image


### List

-V2 Add icons?

**Comment by corsacca** [comment]
Don't save values for empty translations
image

**Comment by corsacca** [comment]
Ordering for the field options is on `order` key on the field:
image

**Comment by prykon** [comment]
This was a big one! 😆

**Pull request merged**
