### PR TITLE
Accordion improvement - Content Filter

### PR DESCRIPTION
**Pull request by blachawk**
Attempting to improve accordion flexibility related to issue #773

### CODE REVIEW

**Comment by corsacca** [comment]
You could put the code in the list.js so it is only loaded on the list page.
The code expect there to just be one open at a time. Here the "All contacts" values get overwritten with 0s when i use filters in the subassigned section
image

Can the default opened section still be blue?

**Comment by blachawk** [comment]
Will do....

**Comment by blachawk** [comment]
The latest push to now have all of my custom code placed in list.js
It also has the multiExpand option set to false for this specific Accordion so that internal logic works properly.

Let me now if anything more is needed.

**Comment by corsacca** [comment]
Hey, 
I am still getting the same issue with multiple lists open at the same time.
When the page loads, can we have the the active menu still be blue?

**Comment by blachawk** [comment]
@corsacca, for cache purposes, please test this update in private mode with Firefox or Incognito mode with Chrome,  Thanks

**Comment by corsacca** [comment]
Thanks @blachawk!

**Comment by mikeallbutt** [comment]
Thanks for working on this @blachawk. The main reason for this issue was actually that it was desired to be able to allow all to be closed - which is especially helpful when using DT on mobile and when a user has a long list of Custom Filters. 

If that mod was implemented, that would be awesome.

**Pull request merged**
