### PR TITLE
Farsi and Turkish Translations

### PR DESCRIPTION
**Pull request by micahmills**
Adding the Farsi Translation and updating the Turkish Translations

### CODE REVIEW

**Comment by micahmills** [comment]
I also updated these in POEditor.com because I didn't know if they get automatically pulled from there or not.

**Comment by micahmills** [comment]
There are still some issues with the context in the Farsi file. I will look at this again in the morning, for now I am going to close this PR, and I will issue a new one when I figure out the problem.

**Comment by micahmills** [comment]
So it looks like my pull request was fine, but I was on the wrong branch locally and didn't have the updated POT file in my current branch. This PR should be ok.

**Comment by corsacca** [comment]
@micahmills wonderful

**Pull request merged**
