### PR TITLE
People Group Typeahead fix

### LINKED ISSUE #1157: Clickable People Group item resolves to 404 page
In the `people group` field the items are clickable but take you to a page that doesn't exist so a 404 is generated.

In the attached image, this is where it looks when the word `Mexican` is clicked. 

https://oikos.disciple.tools/peoplegroups/159

### PR DESCRIPTION
**Pull request by micahmills**
don't include links for peoplegroups typeaheads. fixes #1157

### CODE REVIEW

**Comment by corsacca** [comment]
image
Other fields now look like this

**Comment by corsacca** [comment]
I think we also have a permission error. I tried to add a translation on a people group, but got an insufficient permissions error.

**Comment by micahmills** [comment]
> image
> Other fields now look like this

I think the latest commit fixes this.

**Review by corsacca — COMMENTED** [review]
@micahmills did you see these two?

**Comment by corsacca** [comment]
Thanks @micahmills

**Pull request merged**
