### PR TITLE
testing Enhance/notifications/howlongago

### PR DESCRIPTION
**Pull request by blachawk**
This is an enhancement request to improve the language usage for notifications.  Modifications were also made to apply better handling on the language scope as well.

### CODE REVIEW

**Comment by blachawk** [comment]
@corsacca feel free to test this out on your end.  I tried to make things more glandular with the verbiage.

**Comment by corsacca** [comment]
@blachawk thanks,
Lets use something like this to generate the messages:
`$message = sprintf( __( '%s days ago', 'disciple_tools' ), $number_of_days );`
This way we don't have to translate each individual message.

Can we show:
- the exact number our hours if i was <24 hours ago.
- the exact number of days if < 2 weeks
- the exact number of weeks if < 2 months
- the exact number of months if < 1 year
- the exact number of years after that.

ex 2 hours ago, 3 days ago, 5 weeks ago, 10 months ago, 10 years ago.

Thanks for your work! :)

**Comment by corsacca** [comment]
image
@blachawk can you check the notifications again? I'm not getting the message for all of them

**Comment by blachawk** [comment]
I found the issue...my months and years calculation were off.  I didn't have a use-case to test against them, but now I do.  I have a fix for this. Update coming in a couple hours.

**Comment by corsacca** [comment]
Hey. Apart from the travis issue is this ready? I can build the minified scss to fix it when it is ready.

**Comment by blachawk** [comment]
> 
> 
> Hey. Apart from the travis issue is this ready? I can build the minified scss to fix it when it is ready.

**I am so such an idiot.**  I had was so focused on fixing the issue on an old, old, old branch :smile:  I should of just got a fresh copy of the lasted DT master branch and built my solution off of it!

To answer your question, yes, other than the Travis issue, "that page modification" for **notifications.php** is updated and works locally for me.  That is really the only page you need to add to the DT master branch.  The rest of this branch is gonna right to the trash :smile:

**Comment by corsacca** [comment]
Thanks @blachawk !!

**Pull request merged**
