### PR TITLE
#2313 - Object Caching Enabled Check

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #2313 
---
 
Screenshot 2024-07-12 at 10 49 10

### CODE REVIEW

**Comment by corsacca** [comment]
@kodinkat 
I think this solution addresses local object caching instead of server level object caching. Is that right?

**Comment by kodinkat** [comment]
> @kodinkat I think this solution addresses local/wordpress object caching instead of server level object caching. Is that right?

Yes, the cache for running WP instance, should be cleared accordingly; as hosting server provider approaches towards object cache management may vary.

**Comment by corsacca** [comment]
This Issue is primarily to do with server side object caching as wordpress caching does not seem to be an issue.
Hence the access to a server with server side object caching enabled.

**Comment by corsacca** [comment]
I'm closing this PR for now. It seems like we might need a different approach to figure this one out.

**Comment by corsacca** [comment]
Thanks @kodinkat for your time testing the approach

**Pull request closed without merging**
