### PR TITLE
#2243 - Ability To Import Custom Post Types In Utilities > Import 

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #2243 
---

- A new export view; which now supports the direct exporting of specific settings.

Screenshot 2023-12-13 at 13 31 33

- Upload previously exported json configuration file.

Screenshot 2023-12-13 at 12 46 40

- Customise import requirements.

Screenshot 2023-12-13 at 12 47 31

1. Click record type to view details and make import selections.
2. Select Import Tiles & Fields checkbox, to ensure record type is included within final import.
3. Cherry-pick actual tiles and fields to be included.
4. Review selected import options by record type.
5. Click import button, to execute actual import process.

- Confirm final prompt to start actual import process.

Screenshot 2023-12-13 at 12 47 58

- On completion, review displayed import summary.

Screenshot 2023-12-13 at 12 48 30

### CODE REVIEW

**Comment by corsacca** [comment]
Great start.

We'll want a way to select which custom post types get installed.

**Comment by corsacca** [comment]
@kodinkat am i missing something?
- Create a custom tile and fields in contacts.
- Export just D.T customizations
- Import the file.
- Contacts post type does not appear as an option to select tiles and fields from

**Comment by corsacca** [comment]
@kodinkat this looks good!
2 changes:

- Move import button
- Import Record Type Settings default to checked on post types that are not created yet.
Screenshot 2024-01-31 at 11 49 03 AM


What does unchecking "Import Record Type Settings" uncheck all the selected tiles and fields?

**Comment by kodinkat** [comment]
> @kodinkat this looks good! 2 changes:
> 
> * Move import button
> * Import Record Type Settings default to checked on post types that are not created yet.
>   Screenshot 2024-01-31 at 11 49 03 AM
> 
> Why does unchecking "Import Record Type Settings" uncheck all the selected tiles and fields?

@corsacca Current logic interprets unchecked `Import Record Type Settings` as post type to be excluded from  final import. Therefore, all associated tiles & fields are also unchecked and removed from import selections; to reflect this.

Re-checking `Import Record Type Settings` would also result in the default checking of subsequent tiles & fields.

In terms of the desired flow, are you wanting previously checked tiles & fields to remain untouched regardless of the `Import Record Type Settings` checked state?

**Comment by corsacca** [comment]
@kodinkat 
On a new instance i imported conversations, but `234oaentu oneuth aoetuhsntheuoa s` post type was imported too.

image

**Pull request merged**
