### PR TITLE
chore: add husky and lint-staged to lint staged php files

### LINKED ISSUE #1693: git pre-commit hook to check code before commiting
add a precommit hook to git to check that php files pass the phpcs standards check.

This will prevent lots of commits to the theme where the only thing that is fixed is a small fix for phpcs errors.

One suggestion by @cairocoder01 is to add a post install script to the `package.json` scripts which copies a script into the `.git` pre commit folders.

as in [precommit script](https://github.com/maarifa-org/dt-maarifa/blob/master/git-hooks/pre-commit) and [npm script](https://github.com/maarifa-org/dt-maarifa/blob/master/composer.json#L8)

Another method could be to use `husky` and `lint-staged` npm packages to create the commit hooks on `npm install`

as in [using husky and phpcs](https://sebastiandedeyne.com/running-php-cs-fixer-on-every-commit-with-husky-and-lint-staged/)

My personal leanings are towards the husky method, as all that requires to get the hooks set up is to run `npm install` which all new developers will be doing as part of their dev environment setup anyways.

It also allows to easily add any other pre-commit hooks easily for example if we started using `prettier` or `eslint` at any stage.

What are your thoughts @corsacca or @cairocoder01 ?

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #1693

### CODE REVIEW

**Comment by squigglybob** [comment]
I don't know if it will work correctly on windows/macs :/ but should work on windows if people are using git bash or something.

**Comment by corsacca** [comment]
`npm install`
```
~/code/sites/multisite/app/public/wp-content/themes/disciple-tools-theme$ git commit -m "test"

> disciple-tools@0.1.0 pre-commit
> npx lint-staged

✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
[test-precommit 48b50e44] test
 1 file changed, 3 insertions(+), 2 deletions(-)
``

**Comment by corsacca** [comment]
@kodinkat Can you give this one a test on Mac?

**Comment by kodinkat** [comment]
> @kodinkat Can you give this one a test on Mac?

Can confirm Husky/Lint-Staged checks executed following a local commit:

```
% git add single-template.php
% git commit -m "husky-test"

> disciple-tools@0.1.0 pre-commit
> lint-staged

✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
[chore/add-git-precommit-linting 9b3b69c3] husky-test
 1 file changed, 1 insertion(+)
```

Noted checks did not seem to execute when attempted via an IDE commit.

**Pull request merged**
