### PR TITLE
#2342 - Bulk Send Message Core Integration

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #2342 
---
 
Screenshot 2024-02-27 at 11 18 17

Screenshot 2024-02-27 at 11 19 27

### CODE REVIEW

**Comment by corsacca** [comment]
Thanks @kodinkat!!

- 1. It is not showing how many contacts are selected. Like the bulk send app:
image

- 2. the page is refreshing when done instead of displaying this message:

```
49 scheduled to be sent! [See queue](http://multisite.lwp/wp-admin/admin.php?page=dt_utilities&tab=background_jobs)
51 not sent (likely missing valid email)
```

- 3. Don't show SMS as a sending option if twilio is not set up.
- 4. Don't show the email select if email is the only option.

-5. Add a "Emails will be sent form: [email address]

**Comment by corsacca** [comment]
@kodinkat move default_email_address() and default_email_name() to global functions and use the returned values to populate:
image

**Comment by corsacca** [comment]
@kodinkat 0 scheduled?
image

**Comment by kodinkat** [comment]
> @kodinkat 0 scheduled? image

@corsacca 

Screenshot 2024-03-11 at 16 44 18

Screenshot 2024-03-11 at 16 44 34

**Comment by corsacca** [comment]
Thank you @kodinkat!

**Pull request merged**
