### PR TITLE
#1834 + #1962 + #1963 - People Group Updates

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #1834 

Screenshot 2023-04-14 at 10 20 22

- fixes: #1962 

Screenshot 2023-04-14 at 10 21 28

- fixes: #1963 
  - A standalone php script has been created; which can be manually executed to fetch corresponding `location_grid` ids based on input file's longitude and latitude values.
  - The php script expects the following parameters:
  ```sh
  php people-groups-csv-geolocations.php [Input CSV File] [Output CSV File] [Ignore First Row] [Latitude CSV File Index] [Longitude CSV File Index] [DT Geo-Location API Endpoint] [DT Site-Link API Token]
  ```
  - And can be executed as follows:
  ```sh
  php people-groups-csv-geolocations.php /csv/jp.csv /csv/jp-output.csv true 29 30 http://dtdev.local/wp-json/dt/v1/mapping_module/search_location_grid_by_lng_lat 7fc4dc4c.............
  ```

Screenshot 2023-04-14 at 13 25 45

### CODE REVIEW

**Comment by corsacca** [comment]
1. Multiple instantiation:
image

2. Import all related to country?
image

3. Import all has too many simultaneous connections.
Lets try the same method as installing demo data.

4. Installing a people group does not set the location now available in jp-output.csv? should be jp.csv?

**Comment by kodinkat** [comment]
Screenshot 2023-04-25 at 11 57 04

Screenshot 2023-04-25 at 11 57 22

Screenshot 2023-04-25 at 11 57 38

**Comment by corsacca** [comment]
@kodinkat when installing individual people groups also use the country location_grid id

**Comment by corsacca** [comment]
@kodinkat  This one is still on issue:
if i click on "GET LIST" multiple times, it duplicates the requests:
image

**Comment by corsacca** [comment]
Thank you @kodinkat !

**Pull request merged**
