### PR TITLE
New notification drop down #300

### LINKED ISSUE #300: New feature: a new drop-down menu from the notifications icon
<a href="https://github.com/corsacca"></img></a> **Issue by [corsacca](https://github.com/corsacca)**
_Friday Oct 20, 2017 at 13:05 GMT_
_Originally opened as https://github.com/DiscipleTools/disciple-tools/issues/219_

----

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #300 

I've mostly left the styling of the notifications header part the same as on the notification page, with the result that the All/Unread buttons stack on top of each other the same as the page one's do at certain screen widths. Let me know if you want that changed.

### CODE REVIEW

**Comment by corsacca** [comment]
Thanks for the PR! 
The alignment and spacing of the menu items is a bit off:
image
It was:
image

**Comment by ahillbilly** [comment]
Screen_Shot_2021-03-24_at_11_54_41_AM

It looks like you've got all the pieces and followed the mock-up.   We'd like the [All] [Unread] buttons to stay side by side and think it would be better to swap the "Mark All Read / Settings" in the upper right with the "See All" link that takes you to the notifications page.   See attached image.

**Comment by squigglybob** [comment]
Ok, those things are ready to go, but one last question regarding the notification count: do you want it to stay off and up to the right as in... 
image


or more inline and less into the margin as in the figma mockup...
image

**Comment by corsacca** [comment]
@squigglybob that looks a lot better! I think it got messed up at some point.

**Comment by squigglybob** [comment]
sorry @corsacca only just saw your message, so shall i make it more like the second picture?

**Comment by corsacca** [comment]
> sorry @corsacca only just saw your message, so shall i make it more like the second picture?

That would be amazing!

**Comment by squigglybob** [comment]
ok, that should hopefully be it :slightly_smiling_face: 

I've also changed the styling of the notification count on the notification page to match that in the dropdown box (it had the same not quite floating badge number style)

**Comment by corsacca** [comment]
@squigglybob we still want the "settings" and the "mark all as read". They can show up at the bottom instead of the top.

**Comment by squigglybob** [comment]
Ah, sorry, missed the word swap :0/ I'll fix it up tomorrow

**Comment by squigglybob** [comment]
Hopefully this should be good to go @corsacca

**Comment by corsacca** [comment]
:) thanks @squigglybob

**Pull request merged**
