### PR TITLE
#2296 - Lists Sort By Decimal Number Not Working

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #2296

### CODE REVIEW

**Comment by corsacca** [comment]
> DECIMAL(18,4)
@kodinkat what do the 18 and 4 stand for?

**Comment by kodinkat** [comment]
> > DECIMAL(18,4)
> > @kodinkat what do the 18 and 4 stand for?

@corsacca to do with [precision](https://dev.mysql.com/doc/refman/8.0/en/precision-math-decimal-characteristics.html) - number of digits on either side of decimal point.

**Comment by corsacca** [comment]
Is 18 the largest it will go? (why 18 and 4?)

**Comment by kodinkat** [comment]
> Is 18 the largest it will go? (why 18 and 4?)

@corsacca  No reason, just arbitrary numbers... Max on the left side (of decimal point) is 65 and 30 on the right...

**Pull request merged**
