### PR TITLE
Change email subject to always be "Update..."

### PR DESCRIPTION
**Pull request by burntsun**
This will make the emails group better in Gmail's web interface.

### CODE REVIEW

**Comment by corsacca** [comment]
@burntsun do you suggest this just for comment notifications or for all type of notifications? 
Milestone updates, update needed, assignment changes etc all have their own subject line currently:
https://github.com/DiscipleTools/disciple-tools-theme/blob/master/dt-notifications/notifications.php

**Comment by burntsun** [comment]
I think that everything related to a single contact record should be grouped in the same conversation on Gmail. The easiest way to do that is to give it the same subject line. I didn't see those other subject lines, I can go ahead and modify that code too if you approve.

**Comment by corsacca** [comment]
Approved. Your suggestion is a good one. We might revisit it when we do some kind of notification grouping before we send out an email. 
We do loose a bit of information by making all subject lines for a contact the same.

**Comment by burntsun** [comment]
@corsacca OK, in my new commits, I've created a new function `dt_send_email_about_contact`, which makes sure the same subject line is always used, and that a link is always included in the footer of the email body.

**Comment by corsacca** [comment]
@burntsun thanks!

**Comment by corsacca** [comment]
Is it the same for a group? I'm going to test the changes locally.

**Comment by burntsun** [comment]
To be honest, I didn't think about how these changes affects groups.

**Comment by burntsun** [comment]
Nice, I like this teamwork!

**Pull request merged**
