### PR TITLE
Mix/datefieldsv2

### PR DESCRIPTION
**Pull request by blachawk**
Based on @corsacca request from issue #858, here is a null processioning version to saving blank baptism dates under the Progress section for Contacts.  It appears to be saving the empty state, which is what we want.  In addition., this pull request includes...

* Updating the button, per @mikeallbutt  request, to say `Delete Date`, for the purpose of improving metrics.
* Improvements with syncing the Group Detail dates within the Groups section.

Please test and let me know what you think!

### CODE REVIEW

**Comment by blachawk** [comment]
@corsacca was someone modifying the dt-assets/js/group-details.js file where these conflicts are occuring? I don't recall working on this section....

**Comment by blachawk** [comment]
@corsacca Travis CI is complaining about my PR because it can't find `test/includes/functions.php` : line 14 of `tests/bootstrap.php`.  \

```php
if ( !file_exists( $_tests_dir . '/includes/functions.php' ) ) {
    echo "Could not find " .  $_tests_dir  . " /includes/functions.php, have you run tests/install-wp-tests.sh ?" . PHP_EOL; //@phpcs:ignore
    exit( 1 );
}
```

How should I move forward? Thanks!

**Comment by corsacca** [comment]
It looks more like that one travis run had an issue than something is wrong with the code. The other 2 succeeded. I'll consider the travis check as passed.

**Comment by corsacca** [comment]
Clearing the baptism date works well.
Lets make bring it together on one line like this:
image

And then something similar for the group dates?

**Comment by corsacca** [comment]
I added some code to help save the date correctly and some missing translation strings.

**Comment by corsacca** [comment]
Closing this in favor of #899

**Pull request closed without merging**
