### PR TITLE
Major refactoring of contact details partial

### PR DESCRIPTION
**Pull request by grantholle**
I did a lot of cleaning up in the php partial and the corresponding js for the contact details partial.

I noticed the UI was really inconsistent and the template code needed a little love. I also refactored the js that saves the contact details, making things a little more consistent. I think everything is working, but I may have missed something. Let me know. It's a big one 😛

### CODE REVIEW

**Comment by corsacca** [comment]
@grantholle great improvements!
Can you have a look at the travis checks? Some edits aren't making our phpcs rules happy.

**Comment by grantholle** [comment]
This is good now

**Comment by corsacca** [comment]
@grantholle thank you.
what is you reasoning for the single column in the show more?
image

**Comment by grantholle** [comment]
I think that was by accident.

**Comment by grantholle** [comment]
The catch is that the industry uses flexbox for grids (`display: flex`). When hiding/showing things with jquery (`.toggle()`, `.hide()`, `.show()`), it toggles between `display: none` and `display: block`. When it's `block` display, it breaks the grid. Which is what happened here.

**Pull request merged**
