### PR TITLE
#2033 - Comment area covered by record name

### PR DESCRIPTION
**Pull request by EthanW96**
Add scroll-margin-top property to comment-activity-section to offset the fixed header nav bar covering the comment area.

This css property has good browser coverage according to [caniuse](https://caniuse.com/?search=scroll-margin-top) and [csstricks](https://css-tricks.com/hash-tag-links-padding/) suggests using it. I'm welcome to other suggestions though if alternatives exist I'm not aware of.

#2033

### CODE REVIEW

**Comment by corsacca** [comment]
Thanks @EthanW96 !

With 60px i get:
image

Changing `scroll-margin-top` to 160px seems better:
image

It might depend on the size of the top second nav bar?
image

**Comment by EthanW96** [comment]
Yeah it appears so. Do we want to overestimate at 160px (or a bit higher)? Or try something more programmatic?

**Comment by corsacca** [comment]
THanks @EthanW96 !
How does the 160px make it look for you? I'm assuming different browsers and sizes could be playing in to this.

**Comment by corsacca** [comment]
Actually. On brave on a live website `scroll-margin-top: 60px;` works great. MIght just be my local dev.

**Comment by corsacca** [comment]
@EthanW96 lets go with the 60px version

**Comment by EthanW96** [comment]
@corsacca awesome! I've set it to 60px.

**Comment by corsacca** [comment]
Thank you @EthanW96!

**Pull request merged**
