### PR TITLE
Fix #416

### LINKED ISSUE #416: Highlight current tab in navbar
image
If you are on a contact or in the contacts list make it apparent on the contacts tab.

### PR DESCRIPTION
**Pull request by grantholle**

### CODE REVIEW

**Comment by corsacca** [comment]
Awesome @grantholle !
image

Tho have a look at the metrics tab, each row is highlighted:
image

**Comment by grantholle** [comment]
That's actually a separate bug. The css I did is qualified to `.top-bar`. The metrics's menu style is coming from Foundation's `_main.scss` file. It's being generated by a mixin:

```scss
@mixin menu-state-active {
  background: $menu-item-background-active;
  color: $menu-item-color-active;
}
```

**Comment by corsacca** [comment]
@grantholle, i'm adding a `.top-bar` selector to the js so the active class is only applied on the nav bar.
https://github.com/DiscipleTools/disciple-tools-theme/commit/062b7071c018e5bdf64e1a7916b81d18a0e619d9

**Comment by grantholle** [comment]
Oh yeah... duh. Smart

**Pull request merged**
