### PR TITLE
#1958 - Fixed Issue Custom Field Option Translations Not Being Saved

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #1958

### CODE REVIEW

**Comment by kodinkat** [comment]
@corsacca ready for review.

**Comment by corsacca** [comment]
@kodinkat 
_POST still contains all the translation fields.
image
Which means same rows might now be saved

**Comment by corsacca** [comment]
Clicking "save" calls the `update_custom_field_option_translations` and the Normal POST request?

**Comment by corsacca** [comment]
Thanks @kodinkat !

**Pull request merged**
