### PR TITLE
digital responder can access the contacts based on location

### PR DESCRIPTION
**Pull request by athakur138**

### CODE REVIEW

**Comment by athakur138** [comment]
A user with a role assigned as digital responder only able to access the site contacts within his location grid. e.g. a digital responder is assigned location dubai then he has the access of the contacts under Dubai or cities under dubai.

**Comment by corsacca** [comment]
Thank you @athakur138 for the Pull Request!
We appreciate your interest in Disciple.Tools and your contribution to the code.

I think i understand the goal. Currently a digital responder can be given access to certain sources. So if they have access to the "Web" source, then they have permission to access all contacts that have the source "Web".
This could be expanded to locations. So a digital responder can be given access to all contacts that are in location "France".

We would love to see this feature developed in a plugin. This will let you (and perhaps others) test the functionality. When it is complete we can talk about if it should stay in the plugin or be merged into the core of the theme.

We have a great started template to get started on plugin development and extra documentation here: https://developers.disciple.tools/#create-your-own-plugin

I will paste below some code that we had written for someone who was interested in something similar (untested).

---
I would like to note the the digital responder is able to update the locations that they are responsible for. It appears that they would be able to give themselves access to more contacts this way if that field is used.

Shoot me an email at corsacca@gmail.com and i'll connect you with more recources.

**Comment by corsacca** [comment]
(untested) Code that can be used in a plugin to give a user access to all `access` contacts in a location.

```
public function __construct(){
        add_filter( "dt_filter_access_permissions", [ $this, "dt_filter_access_permissions" ], 20, 2 );
        add_filter( "dt_can_view_permission", [ $this, 'can_view_permission_filter' ], 10, 3 );
        add_filter( "dt_can_update_permission", [ $this, 'can_update_permission_filter' ], 10, 3 );
    }

    public static function dt_filter_access_permissions( $permissions, $post_type ){
        if ( $post_type === "contacts" ){
            //give user 12 access to all contacts in location 100089652
            if ( get_current_user_id() === 12 ){
                $permissions[] = [ "location_grid" => [ "100089652" ] ];
            }
        }
        return $permissions;
    }

    public function can_view_permission_filter( $has_permission, $post_id, $post_type ){
        if ( $post_type === "contacts" ){
            if ( get_current_user_id() === 12 ){
                $locations = get_post_meta( $post_id, "location_grid", false );
                if ( in_array( "100089652", $locations ) ){
                    return true;
                }
            }
        }
        return $has_permission;
    }
    public function can_update_permission_filter( $has_permission, $post_id, $post_type ){
        if ( $post_type === "contacts" ){
            if ( get_current_user_id() === 12 ){
                $locations = get_post_meta( $post_id, "location_grid", false );
                if ( in_array( "100089652", $locations ) ){
                    return true;
                }
            }
        }
        return $has_permission;
    }
```

**Comment by corsacca** [comment]
Note: For the theme, but also for plugins, we require that code pass the phpcs security and styles tests: 
https://developers.disciple.tools/code-contribution/contribution-guidelines

**Pull request closed without merging**
