### PR TITLE
fix: iron out warnings/errors/deprecations from PHP 8.0 upgrade #1384

### LINKED ISSUE #1384: Make sure D.T runs with php8
With `WP_BEBUG` on, errors are being thrown on the list page and probably more places.

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #1384

### CODE REVIEW

**Comment by squigglybob** [comment]
A couple of deprecation warnings for a vendor package of posts-to-posts are fixed in a PR on the (scribu repo)[https://github.com/scribu/wp-scb-framework/pull/60]

**Comment by squigglybob** [comment]
Ok @corsacca , here's where I am currently. I have currently made code changes to remove WP_DEBUG warnings/errors.
I also wanted to make sure that the phpunit tests would run under php8.0

Here's what I've hit so far

## Environment:

Using docker-compose with `mysql:5.7` image, and `wordpress:php8.0` image in which i'm globally installing phpunit so as not to include any phpunit dependencies in our `composer.json`

Installing any version of phpunit below version 8.0 results in the error 

```
Package phpunit/phpunit at version ^6.0 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:  
    - phpunit/phpunit 6.5.14 requires php ^7.0 which does not match your installed version 8.0.6.
```

However using `phpunit ^8.0` results in the wp error

```
root@76c68c1e686a:/var/www/html/wp-content/themes/disciple-tools-theme# ~/.composer/vendor/bin/phpunit 
Error: Looks like you're using PHPUnit 8.5.19. WordPress requires at least PHPUnit 5.4 and is currently only compatible with PHPUnit up to 7.x.
Please use the latest PHPUnit version from the 7.x branch.
```

I have also tried installing `phpunit ^6.0` outside the docker container (so in my own php 7.x local environment so there are no complaints) in the vendor folder within the theme and then running it within the docker container (php 8.0 env) and the phpunit test runs fine, but i'm not sure what downsides there would be as the lower versons of phpunit are not technically compatible with php8.0

Any thoughts would be greatly appreciated :)

**Comment by corsacca** [comment]
@squigglybob 
Thank for this research!
Let's fix the errors in the theme display, and wait for phpunit upgrades when it is supported.

**Comment by corsacca** [comment]
@squigglybob would this one be ready then?

**Comment by squigglybob** [comment]
@corsacca yes i think so

**Comment by corsacca** [comment]
thanks @squigglybob !

**Pull request merged**
