### PR TITLE
implemented a textarea 

### PR DESCRIPTION
**Pull request by micahmills**
implemented the JS and PHP to create the input and save the text.

This addresses #1049.

### CODE REVIEW

**Comment by micahmills** [comment]
This seemed to easy so we need to make sure we double and triple check that this doesn't break something.

**Comment by corsacca** [comment]
Thanks for taking this one on!

I created a textarea in the wp admin.

Here are areas we'll need to look at:
- The value from the create new page was not saved.
- Updating the value on the record should create an activity message.
- When adding the field to the list page the cell remains empty.

**Comment by micahmills** [comment]
@corsacca I fixed the places you mentioned. I have looked for other places that might be a problem don't see any.

**Review by corsacca — APPROVED** [review]

**Comment by corsacca** [comment]
Thanks @micahmills !

**Pull request merged**
