### PR TITLE
Web components integration into new contact form

### PR DESCRIPTION
**Pull request by Ashima-Arora**
Hi @micahmills  @gp-birender ,

As we have started following new approach as per this document( https://github.com/DiscipleTools/disciple-tools-web-components/blob/master/documentation/docs/architecture/services.md)

We have initialize the component service for binding the web components with WP API,

Question: please let us know your thoughts on its placement in the theme.

### CODE REVIEW

**Comment by micahmills** [comment]
What we are working for with implementing web components is to eventually get rid of the jQuery that is being used throughout the theme. So eventually most of the jQuery code in new-record.js will be removed because the ComponentServices.js will handle collecting the data and sending it over via the API.

**Comment by Ashima-Arora** [comment]
@micahmills  @gp-birender 
Thanks, Micah! 
Keeping suggestions into consideration, we are current focus on changing the code in **new-record.js** to make the required changes for **'Create contact form'**. And we are using componentService.js and apiService.js directly to send and receive data.

**Comment by Ashima-Arora** [comment]
Hi @micahmills 

We have added new commit which has recent changes regarding dt- web-components integration except dt-location.
Kindly provide your feedback. Thanks!

@gp-birender @vijenderrr

**Comment by Ashima-Arora** [comment]
@micahmills 

We have some changes in **" src\services\componentService.js "** - Web-components repo, to fix it.  While we were facing this same issue we made some changes in the above-mentioned file.

@gp-birender

**Comment by Ashima-Arora** [comment]
@micahmills 

Kindly see the changes in another web-components PR - 
https://github.com/DiscipleTools/disciple-tools-web-components/pull/74/files#diff-5a3c9f9a36ac1c7c540cb605491cbd9e762d50583d8428fa9d60e28f19563028R43

**Comment by micahmills** [comment]
This looks good, for some reason it is failing the PHPCS checks. I will see if I can resolve that.

**Comment by micahmills** [comment]
Thank you @Ashima-Arora and @gp-birender. I was finally able fix the failing tests and get this merged in to the next branch.

**Pull request merged**
