### PR TITLE
Firebase Login: style background to match normal login

### PR DESCRIPTION
**Pull request by cairocoder01**
- Change background to same gray as standard WP login
- Remove H1 heading that doesn't exist on standard WP login
- Remove "Home" link at bottom of login (login page is the home page if you're not logged in)
- Align "Remember Me" and "Login" button on same line, like standard WP login
- Update URLs sent to Firebase for TOS and Privacy Policy

### CODE REVIEW

**Comment by corsacca** [comment]
Changes. New on left:

image

@cairocoder01 

> Change background to same gray as standard WP login

👍 

> Remove H1 heading that doesn't exist on standard WP login

We'd like to at least keep the heading when user registration is enabled and the user clicks "Register". 

> Remove "Home" link at bottom of login (login page is the home page if you're not logged in)

We want this button for sites where a porch/landing page is used like prayertools: https://ramadandemo.pray4movement.org/. The best solution moving forward might be to make a setting to enable the home button.

> Align "Remember Me" and "Login" button on same line, like standard WP login

Awesome

> Update URLs sent to Firebase for TOS and Privacy Policy

Thanks!

**Comment by cairocoder01** [comment]
@corsacca That makes sense for those two items. I've reverted those changes. It might be nice to have configuration options for both of them. For the sake of time, I didn't do that in this PR.

**Review by squigglybob — APPROVED** [review]
All looks good to me.

I think we will need a filter/shortcode args for adjusting the tosUrl and privacyPolicyUrl
I'll add that as another issue

**Comment by squigglybob** [comment]
Thanks @cairocoder01 🎉

**Pull request merged**
