### PR TITLE
Enhancement/lists

### PR DESCRIPTION
**Pull request by blachawk**
This enhancement is a response to #732 
It will show the last modified date for contacts on the contact page.  The column is sortable.  And each row value will change with the given "contact details" are modified.

### CODE REVIEW

**Comment by blachawk** [comment]
I want to cancel this request at the moment because it appears that **contact-enpoints.php**, is one file, which needs to be re-factored to include a last_modified value for "each" contact.  Without doing that, the last_modified value shows the same for every single contact.  I will need assistance in setting that up.

**Comment by corsacca** [comment]
@blachawk the last_modified field is returned in the results:
image
And the list is built in the js. I don't think we need to refactor the php.

**Comment by blachawk** [comment]
@corsacca I get the samee results but when you convert the value to php date() format, it's identical dates for every row.

**Comment by corsacca** [comment]
try moment.unix( contact.last_modified ).format("YYYY-MM-DD")

**Comment by blachawk** [comment]
Still stuck.  `contact.last_modified` appears unavailable in contacts-endpoint.php

**Comment by blachawk** [comment]
Please test my efforts from pull request #842 Closing #838

**Pull request closed without merging**
