### PR TITLE
feat: click tag to create filter #863

### LINKED ISSUE #863: Tags: clickable tag to create a list/filter
Have a tag (that is in the tags field of the other tile of a contact) be clickable so that when clicked, it creates a list/filter of contacts or groups that have that tag.

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #863

### CODE REVIEW

**Comment by corsacca** [comment]
This looks brilliant.

**Comment by squigglybob** [comment]
Hi @corsacca This PR is ready to go for review I think :)

**Comment by corsacca** [comment]
Thank you @squigglybob 
To simplify I think we could remove the name part of the filter, and have it default to the 'Custom Filter' as you do here: https://github.com/DiscipleTools/disciple-tools-theme/pull/1297/files#diff-f4c9631e9bb5cbd0faec26098367fc3c1eb03a42b1df5e238c0fe29bd9f8a5a7R130
The label is what is displayed.

Will this setup handle a multiple field query?
ie: overall_status: 'active', seeker_path: 'met'
or tags: ['tag_1', 'tag_2' ]

**Comment by squigglybob** [comment]
No worries @corsacca. Yes it will handle multiple field query, each filterLabel query param defines a new field query, and then they all get built together into a custom query.

Also just to clarify, do you want me to remove the optional queryparam `filterName` ?

**Comment by corsacca** [comment]
@squigglybob Yeah. Please remove it, i'm looking at the list code and the name field does not look like it is being used.

**Comment by corsacca** [comment]
`fieldQuery` is maybe better too.

**Comment by squigglybob** [comment]
ok @corsacca those last query param name changes are done also

**Comment by corsacca** [comment]
Thanks @squigglybob looks good.
I created a tag `this&that` and the list doesn't seem to filter to it. Is that the same for you?

**Comment by squigglybob** [comment]
Yes, i'm getting the same thing.

Hmmm. It looks like the ampersand & is  [not being encoded by encodeUri](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) it doesn't encode 

Not Escaped:

    A-Z a-z 0-9 ; , / ? : @ & = + $ - _ . ! ~ * ' ( ) #

It looks like `encodeUriComponent` should do the trick though...

**Pull request merged**
