### PR TITLE
Issue 708

### PR DESCRIPTION
**Pull request by cwuensche**

### CODE REVIEW

**Comment by corsacca** [comment]
@cwuensche 
The cookie didn't save for me when i had more than 30 records.
We can put the code in the details.js instead of the contacts.js and the groups.js, this way it will work for any post type.

**Comment by corsacca** [comment]
If we just save an array of the ids, we can generated the links to the prev and next by looking at the position in the array.

**Comment by cwuensche** [comment]
I have almost finished this. I changed the code so IDs are saved instead of entire posts. I'm working on implementing code that will fetch posts based on the ID so I can populate the next/prev links.

**Comment by corsacca** [comment]
@cwuensche awesome. This seems to work well.
Would you be able to but the prev and next links as buttons in the top right?
Something like:
image

**Comment by cwuensche** [comment]
@corsacca I added a navigation arrow on the left and right side of the bar. Let me know what you think about the way I did it. I used the original image as an example, but we could change it to display like how you have it here, except on the right side of the navigation bar.

**Comment by corsacca** [comment]
This is looking great @cwuensche!
We are liking the icon placement.
A couple changes:
- set the height to 20px 
- have a hover text with "previous record" and "next record"
- have the icons show up on mobile view too on each side on the other icons:
image

**Comment by cwuensche** [comment]
@corsacca I haven't pushed the changes yet, but it seems like it would respond better if I had the arrows on both mobile and desktop view right next to each other like you have in the image on this page. While I was resizing the browser on desktop, the arrows started going to the next line. It would probably work better having the arrows side by side like you have on both desktop and mobile.

**Comment by corsacca** [comment]
Hey @cwuensche ,
I'm still seeing the large icons:
image
Is that the same for you?

**Comment by corsacca** [comment]
Thanks @cwuensche !

**Pull request merged**
