### PR TITLE
Record Details: Clickable social links

### PR DESCRIPTION
**Pull request by corsacca**
Addresses issue: https://github.com/DiscipleTools/disciple-tools-theme/issues/1209

### CODE REVIEW

**Review by micahmills — APPROVED** [review]
There just appears to be the lodash changes that need to be made and this should be good to go. This does did serve as a good test to make sure Travis catches those in the future.

**Comment by corsacca** [comment]
Ha. I should have waited for travis to run. 
```
/home/travis/build/DiscipleTools/disciple-tools-theme/dt-assets/js/details.js
  834:25  error  Please don't use _. for lodash as it conflict with underscore!  no-restricted-syntax
  850:37  error  Please don't use _. for lodash as it conflict with underscore!  no-restricted-syntax
  850:74  error  Please don't use _. for lodash as it conflict with underscore!  no-restricted-syntax
```

**Review by micahmills — APPROVED** [review]
Looks Good

**Comment by corsacca** [comment]
> Looks Good. I assumed you left the _. there on purpose just to test Travis. : )

I copied the code from pre V1, I didn't even think about it.

**Pull request merged**
