### PR TITLE
Bh/bug/contacts/cleardatepicker

### PR DESCRIPTION
**Pull request by blachawk**
This bug fix if for issue #643 
This is a first attempt in offering members the flexibility in leaving the baptism date blank if they really want to do that.  Everything else should still be operational (i.e. setting a date and/or changing it).

Let me know!

### CODE REVIEW

**Comment by corsacca** [comment]
@blachawk looks good.
What is your assessment on adding a button to clear the date? 
I think all it would need to do is empty the input and send an api request to update the contact

**Comment by blachawk** [comment]
Please review my latest efforts in pull request #858 which includes this progress.

**Comment by corsacca** [comment]
Should we close this PR then?

**Comment by blachawk** [comment]
Yes please.  Thanks!

**Pull request closed without merging**
