### PR TITLE
#2388 - Export/Import DT Contacts Using Default WP Feature

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #2388 
---

- Ensure custom post type are available during default WP Exports.
- Note: Target system must already contain post type, in order to successfully import records. See screenshots below:

Screenshot 2024-03-06 at 12 57 25

Screenshot 2024-03-06 at 12 46 02

Screenshot 2024-03-06 at 12 46 41

Screenshot 2024-03-06 at 12 48 23

Screenshot 2024-03-06 at 12 49 34

Screenshot 2024-03-06 at 12 50 42

### CODE REVIEW

**Comment by kodinkat** [comment]
Screenshot 2024-03-13 at 17 10 37

**Comment by corsacca** [comment]
@kodinkat What is the list of default fields that will not export and import?

**Comment by kodinkat** [comment]
> @kodinkat What is the list of default fields that will not export and import?

Screenshot 2024-03-14 at 12 42 44

**Comment by corsacca** [comment]
Thanks @kodinkat! This is helpful. I moved some content to https://disciple.tools/user-docs/features/wp-export-and-import-contacts/

**Pull request merged**
