### PR TITLE
disables private checkbox in wp-admin for default fields.

### PR DESCRIPTION
**Pull request by micahmills**

### CODE REVIEW

**Comment by corsacca** [comment]
Nice solution! Works perfectly, except for name field for some reason:
image

**Comment by micahmills** [comment]
That is strange, for some reason `name` is not a key in the defaults array.

**Comment by micahmills** [comment]
So now all fields that are created as a default or through a plugin will not be allowed to be made private.

**Comment by corsacca** [comment]
that should fix it

**Pull request merged**
