### PR TITLE
Issu987

### PR DESCRIPTION
**Pull request by Filmscore88**
Finalized Issue 987, adding comment replies for all comments in a nested format.

### CODE REVIEW

**Comment by corsacca** [comment]
@Filmscore88 Thanks for the Pull request.
The reply functionality works!

Here is why I see on my screen:
image
On smaller screens the box overflows the space:
image

**Comment by corsacca** [comment]
I know you've put a lot of work in to this already. And the theme changed a bunch in the V1 release.
Would you be able create a PR with just the changes related to this feature?

I see a bunch of stylistic changes like:
image

These are probably done automatically by the IDE. The issue is that they make the changes very hard to review and have broken functionality on us before.

**Comment by Filmscore88** [comment]
Yes I can do that!
Is it only CSS?

**Comment by Filmscore88** [comment]
So I have had a separate repo that I use to see the live changes and one
with the code I'm committing and pushing to github.  I could not figure out
if the branch i'm working on was connected to the live. The problem was
that the code I was using was not updated like you said. I will fix that
and I'm very surprised that those quote marks change the style? Wow, I had
no idea. Finally, I figured out that if I make changes to the
disciple-tools-theme-master folder I can see the changes live so I am doing
that now, I hope that won't be a problem when making the next pull request.

**Comment by corsacca** [comment]
Hey @Filmscore88 
The stylistic changes include: changing double quotes to single quotes or vise version, adding or removing spaces and adding or removing newlines. Most occurrences are in the in the shared-functions.js and comments.js
If you look at the those files in the compare tab on this page you will see what i mean.

**Comment by Filmscore88** [comment]
@corsacca , I made the stylistic changes as well as fixed the css misaligned text box.  I hope it is ok that I commit the changes I made.

**Comment by corsacca** [comment]
@Filmscore88 
If you look at the comments.js in the Files Changed tab on this page you will see what i mean.
Now of these changes are related to the the feature you are developing:
image

**Comment by Filmscore88** [comment]
No those are not related, so I updated my local branch to edit out those things but Im having trouble pushing to the remote repo. I think when I merged master to my branch I did something.

**Comment by Filmscore88** [comment]
Screen Shot 2021-02-04 at 2 08 24 AM

**Pull request closed without merging**
