### PR TITLE
Bug/comments

### PR DESCRIPTION
**Pull request by blachawk**
This is relating to #815, and it may be a **very simple fix** for converting special characters (i.e. quotations) correctly.  We are keeping the entire Lodash process the same,  but simply tweaking the output process of jQuery to use text() instead of html().  We should be using text() over html() when dealing with inputs, wherever possible.

Please feel free to test this out and let me know.

### CODE REVIEW

**Comment by corsacca** [comment]
@blachawk i like this approach
I get an error if the comment is `something <script>console.log("test")`
this seems to fix it:
`comment.comment_content = $("<div>").text(comment.comment_content).text()`

When editing a comment `don't` shows up as `don&#39;t` 
`.replace(/&#039;/g, "'");` needs to be `.replace(/&#39;/g, "'");` ?

**Comment by blachawk** [comment]
@corsacca  let me know if these new adjustments make any difference on your end.

**Comment by corsacca** [comment]
Using `comment.comment_content = $("<div>").text(comment.comment_content).text()` instead of 
`comment.comment_content = $("<div>").html(comment.comment_content).text()` at line 393 fixes the issue.
If it is sufficient i'd prefer that than removing all `>` and `<` signs

**Comment by corsacca** [comment]
Unfortunately my suggestion made the initial issue a problem again.
`My script: i don't have "42"`
becomes: `My script: i don&#039;t have &quot;42&quot;` 
I had tested for other cases but forgot this one.

**Comment by blachawk** [comment]
@corsacca in what case was the following causing an issue for you:

```js
comment.comment_content = $("<div>").html(comment.comment_content).text()
```

With this process enabled, and submitting `something <script>console.log("test")` into the comment field, I get the following result listed... `something &lt;script&gt;console.log(&quot;test&quot;)`

That should send a message to the viewer that we are not allowing custom scripts to be processed here.  If that is not what you want, let me know how the end result "should" look for this case.

Many thanks!

**Comment by corsacca** [comment]
Sorry for the back and forth.
I'm not getting any issues any more with: 
`comment.comment_content = $("<div>").html(comment.comment_content).text()`
I must have had something else throwing that.
@blachawk thanks for finding a great solution!

**Pull request merged**
