### PR TITLE
#1836 & #1816 - Workflow Updates

### LINKED ISSUE #1816: Workflows: Ability to remove
Remove tags, connections, etc
Unset fields like dates, etc

### LINKED ISSUE #1836: Workfows: Implement Mapbox locations

### PR DESCRIPTION
**Pull request by kodinkat**
fixes #1836 
fixes #1816

### CODE REVIEW

**Comment by corsacca** [comment]
On a record:
image
2 words when choosing a location in the workflows is not working.
image

**Comment by corsacca** [comment]
@kodinkat 
When 2 fields are present, it won't remove the faith milestone if the Coach of group is not set.
image

**Comment by corsacca** [comment]
@kodinkat 
Why is the best result way at the bottom?
image

should be at the top:
image

**Comment by kodinkat** [comment]
> @kodinkat Why is the best result way at the bottom? image
> 
> should be at the top: image

@corsacca Ok, so; by default typeahead appears to display results accordingly, by query hit relevance. However, within core, the relevance flag seems to be ignored; as the results list is manually built & displayed.

**Comment by corsacca** [comment]
@kodinkat can we mimic the core here too?

**Comment by kodinkat** [comment]
> @kodinkat can we mimic the core here too?

I'll take a look to see how best to work this in....

**Pull request merged**
