### PR TITLE
 Add "created contact" activity item in contact details

### PR DESCRIPTION
**Pull request by burntsun**
This fixes this issue: https://github.com/DiscipleTools/disciple-tools/issues/220

A few of the commits are there just for refactoring. You may want to view this pull request commit by commit.

### CODE REVIEW

**Comment by corsacca** [comment]
@burntsun Could the "Created contact" be the very beginning of the post activity and also include the time in the text?

**Comment by corsacca** [comment]
@burntsun Also this needs to be on the group

**Comment by burntsun** [comment]
I've fixed the "created contact" stuff as requested by @corsacca .

**Comment by burntsun** [comment]
It's also done for groups now, too.

**Pull request merged**
