### PR TITLE
Added icon for Leader Count & replaced other contact fields' icons

### LINKED ISSUE #1141: Leader count icon needed
The group field "leader count" does not have an icon to help identify it.

It needs to be added to a group record page and the create new group page.

### PR DESCRIPTION
**Pull request by mikeallbutt**
Added an icon and set up the base file to access it. (There are actually 2 icons incase you don't like the one I chose.)
Closes #1141 

Also created and placed some other icons for some contact fields.

Screen Shot 2021-02-03 at 23 55 23

### CODE REVIEW

**Comment by corsacca** [comment]
@mikeallbutt what do the changes to the groups page look like?

**Comment by mikeallbutt** [comment]
The leader count and member count on the groups page are the following:

Screen Shot 2021-02-04 at 02 04 47

**Comment by corsacca** [comment]
The 2 coaching icons are the same, just reversed?

**Comment by mikeallbutt** [comment]
> The 2 coaching icons are the same, just reversed?

Yes. Easy way to make it just enough different but still relevant.

**Comment by corsacca** [comment]
Cool. Thanks for the Icons @mikeallbutt

**Pull request merged**
