### PR TITLE
#2400 - Split By - Option To Clear Filters

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #2400 
---

Screenshot 2024-07-26 at 12 31 58

### CODE REVIEW

**Comment by corsacca** [comment]
@kodinkat  sorting label isn't needed

**Comment by corsacca** [comment]
@kodinkat 
If i select the Assigned to Split by and select Corsac. 
- [ ] check filter labels should no longer show "all contacts i can view".
image

From the Contacts assigned to corsac filter (51 contacts). If i choose another split by (faith milestone).
image

If i choose "Baptized 8", which should combine "assigned to Corsac" and "Baptized", the "Assigned to Corsac" filter is deleted and the list show all "Baptized" contacts instead of "Assigned to corsac" AND "Baptized":
image

**Comment by kodinkat** [comment]
@corsacca let me know how revised flow holds up for you...

**Comment by corsacca** [comment]
Thanks @kodinkat!!

**Pull request merged**
