### PR TITLE
Simple select for bool field

### PR DESCRIPTION
**Pull request by corsacca**

### CODE REVIEW

**Review by squigglybob — COMMENTED** [review]
image

How do we want the boolean to display in the Details summary section?
Would it be better to have Yes/No even if it's false?

At the moment it only shows in the details section if it is true, and not if it is false.

**Comment by squigglybob** [comment]
Also I noticed that you can't create a bool field in the DT settings Fields section. Is that something we want to add as well, or if we are just getting a frontend view of a code only bool field?

**Comment by corsacca** [comment]
Good Catch:
image
image

**Comment by squigglybob** [comment]
Sweet, looks good

**Pull request merged**
