### PR TITLE
add edit and help icons

### PR DESCRIPTION
**Pull request by mikeallbutt**

### CODE REVIEW

**Comment by corsacca** [comment]
@mikeallbutt what are these icons for?
Why replace the current help icon with another one?

**Comment by mikeallbutt** [comment]
> @mikeallbutt what are these icons for?
> Why replace the current help icon with another one?

The different color of the help icon is now the same as the general help icon and by having a different color to the normal blue that is used in many other places around DT, should help it stand out more and make it easier to tell users to look for this color icon.

**Comment by mikeallbutt** [comment]
> @mikeallbutt what are these icons for?
These new icons can be used in the DT app and the website to help users know whether the add button is for a contact or a group.

**Comment by corsacca** [comment]
@mikeallbutt we'd prefer to keep the icon blue as it is. Can you rename it back and the green one to -green.svg?

**Comment by mikeallbutt** [comment]
> @mikeallbutt we'd prefer to keep the icon blue as it is. Can you rename it back and the green one to -green.svg?

Is there a way to just not use my changed/suggested file?

**Comment by corsacca** [comment]
Pull requests are accept all or nothing. A solution is a separate PR for each change/feature.

**Pull request closed without merging**
