### PR TITLE
Mix/datefieldsv3 

### PR DESCRIPTION
**Pull request by blachawk**
Resorting back to a previous commit that worked before the merge conflict.

My latest attempt in resolving pull request #864

### CODE REVIEW

**Comment by corsacca** [comment]
@blachawk clearing the group dates looks good!
The button for clearing the baptism date seems to have disappeared. Can you look into that?

**Comment by blachawk** [comment]
@corsacca are you ok with this update?

**Comment by corsacca** [comment]
Hey,  2 things to bring it to the finish line:
- fix the error in the console when clearing a date
- invert the colors (or something similar) so the x button does not jump out as much on the contact details screen
image

**Comment by micahmills** [comment]
hey @blachawk it looks like you need to run gulp to recompile the style.min.css and style.min.css.map. That should fix the Travis CI problems.

**Comment by corsacca** [comment]
@blachawk I added a commit to revert the extra style changes to make the PR clearer for me.
On the group edit modal the dates are not appearing in the inputs:
Screenshot from 2020-04-15 09-47-05

**Comment by blachawk** [comment]
@corsacca  you may be the only one who has write access to this repository to merge pull requests.  The above styles need to be merged into master.  Requesting for permission.

**Pull request merged**
