### PR TITLE
Group date formatting

### PR DESCRIPTION
**Pull request by micahmills**
Fixes Issue #880

### CODE REVIEW

**Comment by corsacca** [comment]
Can we still use the month name? I switch between English and French a lot so i can't tell if this is Jan or Feb.
image

**Comment by corsacca** [comment]
It looks like the contact baptism date also has the some problem with using the site default language. I can open a new issue if you want to keep it separate.

**Comment by micahmills** [comment]
I noticed this yesterday as well. I will take a look at it today and tomorrow.

**Comment by micahmills** [comment]
A new issue isn’t necessary.

**Comment by micahmills** [comment]
The TLDR version of this PR is that PHP/Wordpress doesn't have a easy way to format date strings based on the users locale instead of the servers locale. So I have switched most things to use the timestamp that we were already saving, and then converting that timestamp to a date string in JS, which has much nicer methods for handling these things. Now we don't have to worry about i18n date strings being saved into the DB.

**Comment by corsacca** [comment]
Thanks @micahmills!
If we follow the {timestamp} route for the activity we'll need to get it working in the mobile app as well:
image
We can go that route. An alternative might be to add a meta_date timestamp field to the activity (dt-posts.php ~line 760) which can be used to display a better date.

**Comment by micahmills** [comment]
I am fine with having a Time stamp from the metadata, but if we keep the string with the date in the mobile app or web, it will always appear in the wrong locale if the users locale is different from the DT instance. 

My opinion is we should always store dates as a unix time stamp and then calculate the date in the appropriate locale from the time stamp. I find the tools to calculate that more robust in JS than in PHP.

**Comment by micahmills** [comment]
I created a PR for the mobile app to implement the activity dates as I have done here.

**Pull request merged**
