### PR TITLE
#1663 Navbar improve "more" breakpoint 

### PR DESCRIPTION
**Pull request by EthanW96**
Hi! This is my first time opening a pull request into DiscipleTools. I've begun to use this tool and I hope to contribute as I have time. I found a task (#1663) that looked fairly minor and good for someone new to this repo.

I thought adding a few more breakpoints to more precisely control how that space is used would work well. I'm not sure I caught if those css classes where used elsewhere in the theme so this may not be complete, but I thought I'd go ahead and make the pull request. I've recorded a video of before and after to showcase the difference.

Original: 

https://github.com/DiscipleTools/disciple-tools-theme/assets/8846891/ec1d97dc-0db4-4cc5-b3d4-db6e2165fb06

Current solution:

https://github.com/DiscipleTools/disciple-tools-theme/assets/8846891/78f2012f-e226-4c3c-a6bb-60247e9050a7

### CODE REVIEW

**Comment by corsacca** [comment]
Thank you @EthanW96 and welcome!

This look great.
To finalize the PR, can you run `gulp` to generate the style.min.css and commit that file.

Covered here in the dev docs: https://developers.disciple.tools/local-setup/gulp-js-css

**Comment by EthanW96** [comment]
Awesome @corsacca !
I've run gulp and committed the file that was generated. 

Is there another issue that would be good for a beginner in the repo to work on?

**Comment by corsacca** [comment]
All your changes are nested under `.top-bar-left`, so won't affect other parts of the theme.

**Comment by corsacca** [comment]
Thank you @EthanW96!

**Pull request merged**
