### PR TITLE
Collapsable tiles for issue #749

### PR DESCRIPTION
**Pull request by mikeallbutt**
All tiles have a chevron icon on the top right side which when clicked, opens or closes the tile.

### CODE REVIEW

**Comment by corsacca** [comment]
Hey, thanks for the initial work on this. Please limit the collapsible functionally to the dynamic tiles:
connections, progress and other. (similar for the group).
I'd like to have more discussion before hiding the contact details section (and the name).

**Comment by mikeallbutt** [comment]
> Hey, thanks for the initial work on this. Please limit the collapsible functionally to the dynamic tiles:
> connections, progress and other. (similar for the group).
> I'd like to have more discussion before hiding the contact details section (and the name).

I have done as requested @corsacca but I think the details tile is very large, especially in mobile view) so having the option for a user to have it collapse is a good thing. If they don't want to collapse it then they won't. But if they wanted to and the option isn't there, there they are stuck.

**Comment by corsacca** [comment]
@thanks @mikeallbutt 
We should come back to being able to collapse the details tile. But maybe with a UI upgrade for name to name not to be hidden.

**Comment by corsacca** [comment]
Clicking the help icon still collapses/expands the tile.
There should be a way to exclude the help button from the collapsed js event.  @blachawk would you be up for joining @mikeallbutt in this one?

**Comment by corsacca** [comment]
Implemented in: https://github.com/DiscipleTools/disciple-tools-theme/pull/877

**Pull request closed without merging**
