### PR TITLE
Enhance/timeconverson/howlongago

### PR DESCRIPTION
**Pull request by blachawk**
This pull request is in response to issue #783 
* Notifications should now be user-friendly with stating how long ago a comment was posted.

### CODE REVIEW

**Comment by corsacca** [comment]
@blachawk It looks like the first if statement will match true for most dates:
`if ( $timestamp > $one_hour_ago ) {`
I'd expect the first entry to have the long ago format
image

**Comment by corsacca** [comment]
Hey, you might still be working on this.
This branch shows
image
Master show:
image

**Comment by blachawk** [comment]
@corsacca line #847 from the Travis CI log is throwing an error. Please advise on how I should correct this on my end.  Thanks!

**Comment by corsacca** [comment]
@blachawk It works! :)
image

**Comment by corsacca** [comment]
I like this improvement.
We need to make the strings translatable so it will work is more languages.

It would also be helpful to hover over the sentence to get the exact date.  I'm proposing sending both strings back, the formatted date and the how long ago string so that both can be used as needed.

**Pull request closed without merging**
