### PR TITLE
add border radius to help modals

### PR DESCRIPTION
**Pull request by wzcblair**
Resolves issue #752

### CODE REVIEW

**Comment by corsacca** [comment]
@wzcblair thanks! This looks good for the help modal. We'd like to see the same for the other modals too.

**Comment by wzcblair** [comment]
Those are all the modals that I can find, please let me know if I missed anything.

**Comment by corsacca** [comment]
Thanks @wzcblair!
Would there be any down side to using the `.reveal` class instead?
The reveal class is a requirement of the foundations modal we are using (called reveal): https://get.foundation/sites/docs/reveal.html and then the change would also apply to the modals existing plugins are adding (demo content plugin for example).
Thanks for working on Disciple.Tools with us :)

**Comment by wzcblair** [comment]
Ah, I wasn't sure whether `.reveal` has more general purposes. I've kept some of the other naming changes not related to this issue -- let me know if you'd like them the way they used to be.

**Comment by corsacca** [comment]
Looks great.
The `-modal` adds clarity too. 
Thanks @wzcblair

**Pull request merged**
