### PR TITLE
Enhancements/lists

### PR DESCRIPTION
**Pull request by blachawk**
This is an improvement over my initial attempt with issue #732 and #838 , to see the last modified date for each record.  Please test and let me know if it works on your end!

### CODE REVIEW

**Comment by corsacca** [comment]
Lets only show the date, not the time or the timezone.
image
Also it does not need to show up on mobile.

**Comment by blachawk** [comment]
ahhh - please ignore the last push on this issue.  I wish there was a cancel button for Travis CI.

**Comment by corsacca** [comment]
@blachawk is this on ready?

**Comment by blachawk** [comment]
Yes one should be good to go.  I can confirm that the last modified column is working for me on my local branch, showing the dates formated as `Mon Dec 02 2019`.  And also goes away once in mobile view.

**Comment by corsacca** [comment]
@blachawk thanks you!

**Pull request merged**
