### PR TITLE
Chore/add eslint to husky checks

### LINKED ISSUE #1723: Upgrade eslint to also process staged files
@squigglybob -> Currently Husky isn't running `eslint` on staged files; as only running `phpcbf` on php files.

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #1723

### CODE REVIEW

**Comment by squigglybob** [comment]
this may need the ecmascript version in the parserOptions in `eslintrc.js` to be bumped up to latest to allow `...` spread syntax to pass the checks.

then there are a handful of places in the code where the eslint is failing that can easily be fixed.

**Comment by corsacca** [comment]
@squigglybob can this pass phpcs?

**Comment by squigglybob** [comment]
hopefully :)

**Comment by squigglybob** [comment]
@corsacca this is good to go, although I had a bit of a mare merging in the master branch with the package-lock.json as it had a lot of diffs. I removed it and rebuilt it with `npm i` :/ so hopefully I haven't messed that up

**Pull request merged**
