### PR TITLE
Browser sync

### PR DESCRIPTION
**Pull request by blachawk**
Attempting to improve the experience by... 
* Allowing developers to set their proxy from the command line with Browser-sync.
* Cleaned up some code in the gulp area
* This enhancement connects to #822

### CODE REVIEW

**Comment by blachawk** [comment]
This browser-sync update now allows users to process the following from the command line. (i.e.)
```powershell
gulp browsersync-p --option http://my-local-url
```

Let me now if anything more is needed

**Comment by corsacca** [comment]
@blachawk why are we ignoring the `dt-assets/build` folder in the .ignore?
When the .scss files are changed, they are minified into the build folded and then used in the theme.
See `dt-assets/functions/enqueue-scripts.php` line 87 and 90.

**Comment by blachawk** [comment]
That was an overlook.  This issue is now corrected.

**Comment by corsacca** [comment]
Thanks @blachawk

**Pull request merged**
