### PR TITLE
1390 - Support Common Field Types During Merging

### PR DESCRIPTION
**Pull request by kodinkat**
### Implementation Summary

Updated and provided additional merge support for the following post field types:

- multi_select
- key_select
- text
- textarea
- number
- date
- array
- boolean
- tags
- location_meta
- connection
- communication_channel
- tasks
- private fields

### CODE REVIEW

**Comment by corsacca** [comment]
I get an error: `Sorry, something went wrong: Missing required lng or lat` when merging a contact with a location (added with mapbox enabled)

**Comment by corsacca** [comment]
Note: there is both the `location` and the `locaction_meta` field. A quick test shows that the locations (without a mabbox key) are not being merged.

**Comment by kodinkat** [comment]
> I get an error: `Sorry, something went wrong: Missing required lng or lat` when merging a contact that has a location (added with mapbox enabled)

Safeguards now put in place to ensure lng/lat coordinates are present.

**Comment by kodinkat** [comment]
> Note: there is both the `location` and the `locaction_meta` field type. A quick test shows that the locations (without a mabbox key) are not being merged.

location field type now supported.

**Comment by corsacca** [comment]
no mapbox key:
location_grid fields should be merged like tags. Ie if there is location1 on contactA and location2 on contactB, then the merged record should have location1 and location2
Some for location_grid_meta

**Comment by kodinkat** [comment]
> no mapbox key:
> location_grid fields should be merged like tags. Ie if there is location1 on contactA and location2 on contactB, then the merged record should have location1 and location2
> Some for location_grid_meta

@corsacca ok cool, will refresh memory and take another look at it tomorrow! :)

**Comment by corsacca** [comment]
@kodinkat is the last commit to fix the locations behavior?

**Comment by kodinkat** [comment]
> @kodinkat is the last commit to fix the locations behavior?

@corsacca Yep! Should now be good to go! contactB's location2 is also appended to contactA's location1. Let me know if anything...

**Comment by corsacca** [comment]
@kodinkat  Do you know why
Merging
image
into
image
produces:
image

It added an entry for "Toledo"

**Comment by corsacca** [comment]
Thanks @kodinkat !

**Pull request merged**
